version: '3.9'

services:
  mongo_db:
    container_name: Med_db_container

    image: mongo:latest

    restart: always

    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/server
        - /usr/src/server/node_modules
    environment:
      PORT: 5000

    depends_on:
      - mongo_db
volumes:
  mongo_db: {}
